export const FETCH_TOP_HABITS_SUCCESS = "FETCH_TOP_HABITS_SUCCESS";
export const FETCH_TOP_HABITS_FAIL = "FETCH_TOP_HABITS_FAIL";

export const FETCH_MONTH_STATS_SUCCESS = "FETCH_MONTH_STATS_SUCCESS";
export const FETCH_MONTH_STATS_FAIL = "FETCH_MONTH_STATS_FAIL";

export const FETCH_CATEGORY_STATS_SUCCESS = "FETCH_CATEGORY_STATS_SUCCESS";
export const FETCH_CATEGORY_STATS_FAIL = "FETCH_CATEGORY_STATS_FAIL";
